CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY, email TEXT UNIQUE NOT NULL, name TEXT NOT NULL,
  password_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS docs (
  id SERIAL PRIMARY KEY, user_id INT REFERENCES users ON DELETE CASCADE,
  title TEXT NOT NULL, category TEXT DEFAULT 'Personal', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS chunks (
  id SERIAL PRIMARY KEY, doc_id INT REFERENCES docs ON DELETE CASCADE,
  user_id INT REFERENCES users ON DELETE CASCADE, content TEXT NOT NULL, embedding vector(1024));
CREATE INDEX IF NOT EXISTS chunks_emb ON chunks USING hnsw (embedding vector_cosine_ops);
CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY, user_id INT REFERENCES users ON DELETE CASCADE,
  title TEXT NOT NULL, priority CHAR(1) DEFAULT 'M', deadline DATE, done BOOLEAN DEFAULT false);
CREATE TABLE IF NOT EXISTS profiles (user_id INT PRIMARY KEY REFERENCES users ON DELETE CASCADE, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS projects (id SERIAL PRIMARY KEY, user_id INT REFERENCES users ON DELETE CASCADE, name TEXT NOT NULL, data JSONB DEFAULT '{}');
CREATE TABLE IF NOT EXISTS learn_progress (id SERIAL PRIMARY KEY, user_id INT REFERENCES users ON DELETE CASCADE, topic TEXT, correct INT, total INT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS pres_sessions (id SERIAL PRIMARY KEY, user_id INT REFERENCES users ON DELETE CASCADE, topic TEXT, seconds INT, slides INT, questions INT, helpful INT DEFAULT 0, unhelpful INT DEFAULT 0, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;
CREATE TABLE IF NOT EXISTS chat_messages (id SERIAL PRIMARY KEY, user_id INT REFERENCES users ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
ALTER TABLE docs ADD COLUMN IF NOT EXISTS public BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
